baseURL: "https://geraldmokereke.xyz"
languageCode: "en-us"
title: "Gerald."
theme: "rocinante"
paginate: 8

markup:
  highlight:
    style: "monokailight"
  goldmark:
    renderer:
      unsafe: true

params:
  mainSections:
    - "posts"
    - "photos"
  email: "mail@example.com"
  favicon: "https://i.ibb.co/YNRSK0Z/gerald-logo.png"
  about: |
    I'm Gerald Maduabuchi Okereke. Welcome to my blog. A software engineer exploring Types, Tensors and Distributed systems.
    Here, I write articles about things I'm building, learning and other stuff.

  links:
    - link:
        - name: "My Website"
          href: "https://geraldokereke.xyz"
          new_tab: true
        - name: "Github"
          href: "https://github.com/grayoj"
          new_tab: true
        - name: "X"
          href: "https://twitter.com/geraldabuchi"
          new_tab: true
        - name: "Email"
          href: "mailto:geraldmokereke@gmail.com"
          new_tab: true
